[[presets]]
modules = ["modules/common.nix", "modules/yeet.nix", "modules/disko.nix", "disko/btrfs-subvolumes.nix"]
description = "Simple btrfs disk setup"
# default = true

[[presets]]
modules = ["modules/common.nix", "modules/yeet.nix", "modules/disko.nix", "modules/lanzaboote.nix", "disko/luks-btrfs-subvolumes.nix"]
description = "Secure system with lanzaboote and luks"
