[[presets]]
modules = ["modules/common.nix", "modules/yeet.nix", "modules/disko.nix", "disko/btrfs-subvolumes.nix"]
description = "Simple btrfs disk setup without luks"
# default = true

[[presets]]
modules = ["modules/common.nix", "modules/yeet.nix", "modules/disko.nix", "disko/luksbtrfs-subvolumes.nix"]
description = "System setup with lanzaboote and luks"
